- name: command module
  hosts: local
  connection: local

  tasks:
  - name: command module
    # ansible.builtin.command: cat /etc/passwd | grep root  ansible command doesnt support pipe and redirection
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: user_output

  - name: print output 
    ansible.builtin.debug:
      msg: {{ user_output }}
    