- name: loops advanced
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.value }}"
    loop: #list of map
    - { name: "nginx", state: "absent" }
    - { name: "mysql", state: "present"}
    - { name: "zip", state: "absent"}
  