- name: loops
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: loops
    ansible.builtin.debug:
      msg: " hello {{ item }}" # item is reserved keyword
    loop:
    - kohli
    - rohit
    - dhoni
  - name: install package
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
     
